export const theDevices = [
    {
        "type": "wind",
        "items": [
            { "name": "Device 1", "position": [32.08, 34.77] },
            { "name": "Device 2" },
            { "name": "Device 3", "position": [32.07, 34.78] },
            { "name": "Device 4" },
            { "name": "Device 10" },
            { "name": "Device 11" },
            { "name": "Device 12" },
            { "name": "Device 13" },
            { "name": "Device 14" },
            { "name": "Device 15" },
            { "name": "Device 16" },
            { "name": "Device 17" },
            { "name": "Device 18" },
            { "name": "Device 19" },
            { "name": "Device 20" },
            { "name": "Device 21" },
            { "name": "Device 22" },
            { "name": "Device 23" },
            { "name": "Device 24" },
            { "name": "Device 25" },
            { "name": "Device 26" },
            { "name": "Device 27" },
            { "name": "Device 28" },
            { "name": "Device 29" },
            { "name": "Device 30" },
            { "name": "Device 31" },
            { "name": "Device 32" },
            { "name": "Device 33" },
            { "name": "Device 34" },
            { "name": "Device 35" },
            { "name": "Device 36" },
            { "name": "Device 37" },
            { "name": "Device 38" },
            { "name": "Device 39" },
            { "name": "Device 40" },
            { "name": "Device 41" },
            { "name": "Device 42" },
            { "name": "Device 43" },
            { "name": "Device 44" },
            { "name": "Device 45" },
            { "name": "Device 46" },
            { "name": "Device 47" },
            { "name": "Device 48" },
            { "name": "Device 49" },
            { "name": "Device 51" },
            { "name": "Device 52" },
            { "name": "Device 53" },
            { "name": "Device 54" },
            { "name": "Device 55" },
            { "name": "Device 56" },
            { "name": "Device 57" }]
    },
    {
        "type": "water",
        "items": [
            { "name": "Device 5" },
            { "name": "Device 6", "position": [32.080320121040344, 34.78262901306153] },
            { "name": "Device 7" },
            { "name": "Device 8", "position": [32.0678106134499, 34.768552780151374] }
        ]
    }
];
